DROP DATABASE IF EXISTS TRAVEL_COMPANY;
CREATE DATABASE TRAVEL_COMPANY;
USE TRAVEL_COMPANY;

/* SOLUTION 1 */
DROP TABLE IF EXISTS PASSENGER;
CREATE TABLE PASSENGER (
    Passenger_name VARCHAR(50),
    Category VARCHAR(20),
    Gender CHAR,
    Boarding_City VARCHAR(50),
    Destination_City VARCHAR(50),
    Distance INT,
    Bus_Type VARCHAR(20)
);

DROP TABLE IF EXISTS PRICE;
CREATE TABLE PRICE (
    Bus_Type VARCHAR(20),
    Distance INT,
    Price INT
);
